### ISSUE TITLE
Munin vhost in dspace hosts doesn't work anymore

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#10]
We used to get to the local `/munin` resource using an SSH tunnel like:

``` console
$ ssh -L 3000:localhost:80 -N provisioning@someserver.com
```

And then accessing `http://localhost:3000/munin/` but now it gets re-directed to the Tomcat vhost.

**Comment by oguya** [comment]
This is weird but I think it works - tunneling using ip addresses instead of hostnames.

**steps to reproduce**
- create a tunnel
  
  ```
  ssh -vL 3000:127.0.0.1:80 -N provisioning@leh-server
  ```
- open link on chrome:
  
  ```
  http://127.0.0.1:3000/munin/
  ```
  
  OR
  
  ```
  http://localhost:3000/munin/
  ```

**Comment by alanorth** [comment]
You're right, it works if you set up the tunnel using 127.0.0.1... hmmm.

**Comment by oguya** [comment]
Since we set munin & nginx status vhosts to bind to & serve requests from localhost, then I think we should tunnel via  `127.0.0.1`.
