### ISSUE TITLE
Add support for Debian 8

### ISSUE THREAD

**Issue by oguya** [ilri/rmg-ansible-public#13]
[Debian 8](https://wiki.debian.org/DebianJessie) was released a few months ago & yet we haven't added its support on our playbooks. So far we've played around with the  preseeds[1] & even found a few issues[2] to consider when migrating from older releases.

Anyway, should we add support for debian 8 on our playbooks or not ?
1. https://gist.github.com/oguya/37a93c4f5250adf808d7
2. https://github.com/alanorth/ansible-personal/issues/22

**Comment by alanorth** [comment]
I am not in support of deploying _new_ Debian instances (short life cycle
is annoying), but we do have to remember the few critical Debian 7 boxes we
have that can't be migrated to Ubuntu. In any case, Debian 8 will be a good
experience for systemd, firewalld, IPv6, etc, as those are all coming in
CentOS 7 and Ubuntu 16.04 LTS eventually, so the lessons can be re-used.

On Mon, Aug 3, 2015 at 10:38 AM, James Oguya notifications@github.com
wrote:

> Debian 8 https://wiki.debian.org/DebianJessie was released a few months
> ago & yet we haven't added it's support on our playbooks. So far we've
> played around with the preseeds[1] & even found a few issues[2] to consider
> when migrating from older releases.
> 
> Anyway, should we add support for debian 8 on our playbooks or not ?
> 1. https://gist.github.com/oguya/37a93c4f5250adf808d7
> 2. alanorth/ansible-personal#22
>    https://github.com/alanorth/ansible-personal/issues/22
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ilri/rmg-ansible-public/issues/13.

## 

Alan Orth
alan.orth@gmail.com
https://alaninkenya.org
https://mjanja.ch
"In heaven all the interesting people are missing." -Friedrich Nietzsche
GPG public key ID: 0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0

**Comment by oguya** [comment]
Apart from the `common` role, I don't think there are other roles which any existing Debian 7 hosts run.
Therefore, we should only focus on the `common` role. 

Otherwise, all Debian 8 related changes will be made on [debian-08 branch](https://github.com/ilri/rmg-ansible-public/tree/debian-08).

**Comment by oguya** [comment]
Before migrating to Debian 8(jessie) from Debian 7(wheezy), we need to have a look at potential issues[1] to consider with the upgrade[2] process & new changes to expect.
1. https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html
2. https://www.debian.org/releases/stable/amd64/release-notes/ch-upgrading.en.html

**Comment by oguya** [comment]
Main components of common role tested:
- **Firewall**: Due to the major changes in iptables-persistent[1], I think we should start using firewalld. Besides that, firewalld will is the norm on CentOS 7.
- **cron-apt**: No major changes in Debian 7's cron-apt[2] & 8's cron-apt[3]. `cron-apt` on Debian 8 still uses the good old cron jobs - no systemd timers.
- **sysctl**: No changes in both Debian 7's & 8's `sysctl.conf`, though, we have to test CIS sysctl adjustments on Debian 8.
- **Raid monitoring**: Seems like HWRaid[4] packages doesn't have any packages for Debian 8.
1. https://packages.debian.org/jessie/all/iptables-persistent/filelist
2. https://packages.debian.org/wheezy/all/cron-apt/filelist
3. https://packages.debian.org/jessie/all/cron-apt/filelist
4. http://hwraid.le-vert.net/debian/

**Comment by alanorth** [comment]
I think the only issue here will be the RAID monitoring stuff. I am doing a test on a clean Debian 7 instance now, moving through the upgrade to 8 and then re-provisioning.

**Comment by alanorth** [comment]
There are no megacli packages for Debian Jessie, but it seems the Wheezy ones still work:

https://github.com/eLvErDe/hwraid/issues/19

Keep this in mind.

**Comment by alanorth** [comment]
The common role—firewalld, sshd, ssh keys, packages, etc—runs without errors on my Debian 8 instance (which was a test upgrade from Debian 7). The `megacli` binary from the Debian 7 (wheezy) repo still works, though I don't have LSI hardware on that host so I can't test if it works beyond that.

One further test would be to test how our firewalld tasks work when the remote host has network bridges. Ansible seems to be able to pick the bridge as the "default" interface when constructing the public.xml zone (instead of the slave or virtual Ethernet interfaces) so this might not be an issue.

**Comment by alanorth** [comment]
@oguya After our conversation today, perhaps we can close this and delete the `debian-08` branch? No plans to create any Debian 8 hosts.

**Comment by oguya** [comment]
@alanorth That's right! It's only one host that is still on Debian 7 but we'll go to Ubuntu 16.04 once we get a new replacement.
Goodbye Debian, it's been real :+1:
