### ISSUE TITLE
Switch to using Munin standalone on all machines

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#18]
Munin is kinda old school, but it gives insight into some basic things like memory, disk, CPU, and network VERY easily. We currently pull Munin from a central server, but this is kinda clunky and introduces complexities with host names, firewalls, DMZ, etc, and has led us to not really commit to Munin, and the search for other monitoring / graphing / alerting solutions has taken us down the rabbit hole. Sadly this means that we don't have stats for machines that we really should have them on!

It would be better to just have all machines run Munin locally as a rule, because you can always SSH there and check the graphs with `python -m SimpleHTTPServer` from the munin HTML directory. This also makes our munin playbook more deployable, and frees up one task from the current central server (yay) who really shouldn't be doing it anyways.

**Comment by oguya** [comment]
this should be as easy as removing this line -> https://github.com/ilri/rmg-ansible-public/blob/master/roles/munin/tasks/main.yml#L11   :wink:

**Comment by alanorth** [comment]
Yeah, but also removing the logic for firewalls, the templated settings in munin-node.conf, etc. Also, what's up with that precise check, we don't need no precise anymore!

**Comment by oguya** [comment]
I've also realized munin's `htmldir` on RedHat-based distros is `/var/www/html/munin`—which is of course open to the public if you're running a web server; opsec—whereas Debian-based distros use `/var/cache/munin/www`. 
We can always leave it as the default value, then on RedHat-based distros which run a publicly accessible web server, we'll have to use htpasswd, .htaccess or apache rules to only allow requests from only localhost or to authenticate users.

**Comment by oguya** [comment]
Munin is now in stand-alone in all the things :smile:

**Comment by alanorth** [comment]
Awesome, dude. I know it's not as sexy as Grafana but it's a hell of a lot less moving parts and it just works. Good work. It is incredibly valuable to be able to show trends in simple system resource statistics.

**Comment by oguya** [comment]
Yup! Grafana(grafana + influxdb + collectd) has too many moving parts & it requires some love. Munin on the hand just works out of the box!
