### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#2]
A handful of hosts are running on infrastructure where IPv6 is live (right now only the hosts on Linode). We need to add a few things to our playbooks to take advantage of this:
- [x] ip6tables template
- [x] ipv6 "public" address to ipsets (`::/0`)
- [x] ipv6 listeners for nginx template in dspace role
- [x] add CentOS support
- [x] add firewalld support

**Comment by alanorth** [comment]
nginx should be as easy as adding this to each vhost you want to use IPv6 on:

```
listen [::]:443 ssl spdy;
```

And similar for port 80.

**Comment by alanorth** [comment]
We can add an extra item in the `ghetto_ipsets` list for ipv6src and then iterate over the same lists in the ip6tables template!

```
{% for network in ssh_access %}
{% if ghetto_ipsets[network].ipv6src is defined %}
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -s {{ ghetto_ipsets[network].ipv6src }} -j ACCEPT
{% endif %}
{% endfor %}
```

Of course making sure the wanted rule does exist first! Tested and working on Ubuntu 14.04 and 12.04. Still need to come up with something for CentOS 6 and CentOS 7 (firewalld!).

**Comment by oguya** [comment]
For firewalld we'll use the same zone file template for both ipv4 & ipv6.

All we'll need to do, for each rule, is to specify the ip family. For instance:
_ipv4_ & _ipv6_

```
{% for network in ssh_access %}
<rule family="ipv4">
    <source address="{{ ghetto_ipsets[network].src }}"/>
    <port protocol="tcp" port="22"/>
    <accept/>
</rule>
{% if ghetto_ipsets[network].ipv6src is defined %}
<rule family="ipv6">
    <source address="{{ ghetto_ipsets[network].ipv6src }}"/>
    <port protocol="tcp" port="22"/>
    <accept/>
</rule>
{% endif %}
{% endfor %}
```

**Comment by alanorth** [comment]
FirewallD is starting to look more elegant than iptables... :)

**Comment by oguya** [comment]
I've translated ipv6 rules in ip6tables template to ipv6 firewalld rules.

**Comment by alanorth** [comment]
:thumbsup:

**Comment by oguya** [comment]
I've tested the ip6tables template on CentOS 6 host & it works fine.
For CentOS 7/firewalld, there's not much we can do at the moment since we don't have any machines on it.

**Comment by alanorth** [comment]
I'm not terribly worried about IPv6 on CentOS 6; we only have one host with that setup, and I'll migrate it to Ubuntu at any chance I get!

So what's new here? There are no new tasks for CentOS 6, eh? We just hadn't tested the existing template before?

**Comment by oguya** [comment]
Well, there's a new task for CentOS 6 that copies `ip6tables.j2` template to the target host.
See commit https://github.com/ilri/rmg-ansible-public/commit/25ba55c380e6636c12a4b95fb860dc1913a06402

**Comment by oguya** [comment]
Good to merge [ipv6](https://github.com/ilri/rmg-ansible-public/tree/ipv6) branch into [master](https://github.com/ilri/rmg-ansible-public) branch

**Comment by alanorth** [comment]
doit

**Comment by oguya** [comment]
rebased, merged & pushed!

**Comment by oguya** [comment]
I guess we nolonger need [ipv6](https://github.com/ilri/rmg-ansible-public/tree/ipv6) branch
