### ISSUE TITLE
Ansible 2.0 Readiness

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#22]
In #21 @oguya pointed out that there is an [Ansible 2.0 porting guide](https://docs.ansible.com/ansible/porting_guide_2.0.html) that we should really look at, as some of our playbooks are using old conventions that work now, but will be unsupported by version 2.2.

For example:
- [x] We cleaned up some use of `sudo_user` but there are still more buried in the playbooks (dspace tomcat stuff)
- [x] Don't forget the misc-plays too!

**Comment by oguya** [comment]
@alanorth  I presume you're also using ansible v2.0 from pip or something of the sort, & not relying on just the porting guide, right? :wink:

**Comment by alanorth** [comment]
Does Luke Skywalker ask Yoda if he knows how to use his lightsaber?

**Comment by oguya** [comment]
haha! What an analogy. I guess I'm Yoda, you can be Luke :stuck_out_tongue_winking_eye:

**Comment by oguya** [comment]
In misc_plays, there were a bunch of `sudo` directives that I changed to `become`.
See 29dec59

**Comment by oguya** [comment]
Apart from `sudo/sudo_user` & bare variables in `with_` loops, I don't see any other changes to make.

**Comment by oguya** [comment]
I guess we've been following Ansible best practices to the letter :+1:
If a warning related to 2.0 pops up, we'll just fix it on master, otherwise, this is good to go.

**Comment by alanorth** [comment]
I think you're right, we did some cleanups for good practices at one point last year as well. LGTM.
