### ISSUE TITLE
DSpace role ends up with two postgres installed

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#29]
I'm just doing some Ubuntu 16.04 testing again and it looks like I end up with both PostgreSQL 9.3 and 9.5 installed.

**Comment by oguya** [comment]
Impossibru :angry: !
Anyway, let me reproduce this bug :smile:

**Comment by oguya** [comment]
Chery-picked 4790799 into master

**Comment by alanorth** [comment]
Bravo. So the contrib package was pulling in the distribution's version,
leading to the dependency on the other postgres!

On Wed, Apr 6, 2016, 14:42 James Oguya notifications@github.com wrote:

> Chery-picked 4790799
> https://github.com/ilri/rmg-ansible-public/commit/4790799fa2e30e9c15e5d9bde965132a4b961a4c
> into master
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ilri/rmg-ansible-public/issues/29#issuecomment-206329071
> 
> ## 

Alan Orth
alan.orth@gmail.com
https://englishbulgaria.net
https://alaninkenya.org
https://mjanja.ch
