### ISSUE TITLE
Use timedatectl instead of ntpd on hosts with systemd

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#46]
systemd provides a simple NTP client and we should use it instead of installing `ntp` on Ubuntu 16.04, Debian 8, and CentOS 7. These tasks should work:

```
- name: Set timezone
  when: timezone is defined
  command: /usr/bin/timedatectl set-timezone {{ timezone }}
  tags: timezone, ntp

- name: Enable NTP
  service: name=systemd-timesyncd enabled=yes
  tags: ntp
```

I also set the timezone, as it's known when you deploy the machine on Linode/AWS/Digital Ocean, and should really be set in the host's variables anyways.

**Comment by alanorth** [comment]
I just checked on a clean Ubuntu 16.04.1 installation and the `systemd-timesyncd` is already on by default. I wonder if that's true on Linode Ubuntu images as well. If so, we don't even need to explicitly enable it with `timedatectl set-ntp on`, and probably only need to just stop installing the standalone `ntp` package in our playbooks.

Can you check on an existing Linode 16.04 instance, @oguya? I believe you ran the playbooks there so they should have the standalone `ntp`. Is `systemd-timesyncd` active there too?

**Comment by oguya** [comment]
system-timesyncd is enabled by default on Ubuntu 16.04 Linode instances. But, it won't start if you have ntp installed.

```
# systemctl cat systemd-timesyncd.service
...
[Unit]
ConditionFileIsExecutable=!/usr/sbin/ntpd
...
```

**Comment by alanorth** [comment]
Oh snap, that's great, so there's no harm in enabling it — we basically just need to make sure `ntp` is uninstalled, then enable systemd's NTP client. That should cover all scenarios (on my test VM I just managed to get into a state where `ntp` was uninstalled _and_ systemd's NTP was disabled, so network time was actually off!).

Also, I had been using `timedatectl set-ntp on` as a command in my Ansible tasks, but it seems it's probably more "Ansible-y" to use the service module to enable `systemd-timesyncd`.

**Comment by alanorth** [comment]
Ok, updated pull request #48 to:
- Use ansible's service module to enable `systemd-timesyncd` instead of toggling via forking a `timedatectl` command
- Make sure the `ntp` package is uninstalled on "modern" hosts, and installed on "old" hosts (ie, hosts with and without systemd)

Have a look and give it a try. We could reduce the number of tasks and "when" conditions there by half if we used `{{ ansible_pkg_mgr }}` for the tasks, but ugh, I think that's an anti pattern, eh?

**Comment by oguya** [comment]
you also gotta set a default timezone

**Comment by oguya** [comment]
maybe `Africa/Nairobi`

**Comment by alanorth** [comment]
When you install Ubuntu server from the ISO at least, it asks you for your time zone. I was kinda assuming that Linodes get their time zone from Linode's magic deployment thing, since you pick a data center when creating the host. I will spin one up and check on Sunday (which is a working day here!).

**Comment by alanorth** [comment]
On a clean Ubuntu 16.04 Linode in Frankfurt, DE (which is UTC+2):

```
# timedatectl 
      Local time: Mon 2016-08-22 06:49:37 UTC
  Universal time: Mon 2016-08-22 06:49:37 UTC
        RTC time: n/a
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

Time zone is UTC and the `systemd-timesyncd` service is enabled and running. `ntp` package is not present. So it seems at least for the time zone, we can set it in the host vars if we want, but we could leave `Etc/UTC` as the default if it's undefined (which, incidentally, is correct, as all of our Linodes are in London right now).

**Comment by oguya** [comment]
Even a UK instance uses UTC timezone, as the default TZ. I'm OK, with leaving it as UTC.

**Comment by alanorth** [comment]
So how do you feel about the pull request in its current state? We clearly don't _need_ the task to enable `systemd-timesyncd`, but I think there's no harm in leaving it. Like, we're still not sure about how CentOS 7 handles it (or even if it has `systemd-timesyncd`, to be honest, as I think it only came in a later systemd). Hmm.

**Comment by alanorth** [comment]
BTW, [`systemd-timesyncd` came in systemd 213](https://lists.freedesktop.org/archives/systemd-devel/2014-May/019537.html), and [RHEL/CentOS 7.2 should have systemd 219](http://mirror.centos.org/centos/7/os/x86_64/Packages/), so we're good.

**Comment by oguya** [comment]
We can leave the task to enable `systemd-timesyncd` atleast to cover all corner cases. I think it's a good idea instead of implying or expecting it to be enabled by default.

**Comment by alanorth** [comment]
Great, then #48 looks good to me, ready to merge if you approve. I updated the title/desc so it is no longer WIP.
