### ISSUE TITLE
Promote Java 8 to default in DSpace role

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#49]
Similar to #40 for PostgreSQL 9.5, we need to promote Java 8 to be the default for the DSpace role once we move to the new DSpace + Ubuntu 16.04 stack. [Java 8 is recommended for Solr 4.x](https://wiki.apache.org/solr/ShawnHeisey), which we are currently using with DSpace 5.x.

Also, Java 8 removes the PermGen option from the JVM, so we need to adjust all hosts' `JAVA_OPTS` accordingly before switching.

**Comment by oguya** [comment]
I guess it's just a matter of setting `java_version_major` to 8 & deploying to a new Ubuntu 16.04 Linode instance, right?

**Comment by oguya** [comment]
a bit unrelated: doesn't `java_version_major` sounds like `java_major_version` ??

**Comment by alanorth** [comment]
Yeah, just bump the default and re-run the `packages,java,tomcat` tags to be safe. I picked `java_version_major` and `tomcat_version_major` so that it was obvious that it was only 7 or 8, not 8u101 or 7.54, etc. But looking at Ansible's similar facts for distro version, I should probably change it to match `ansible_distribution_major_version`. What do you think?
