### ISSUE TITLE
Avoid redundant cache update(s)

### ISSUE THREAD

**Issue by oguya** [ilri/rmg-ansible-public#5]
Ansible should only re-synchronize package index files from their sources if the last `aptitude update` run is less or equal to X seconds.
We should do so by adding `cache_valid_time` option in `apt` module[1] and set it to 86400 seconds == 24 HRS

I think this also speeds up the playbook(s).
1. http://docs.ansible.com/apt_module.html

**Comment by oguya** [comment]
I think this should not apply to situation where you've added a PPA in one task & in the subsequent task you install a package from the PPA you added earlier. 

For example: in `solr` role, we add an Oracle Java PPA & then install Oracle Java from the PPA.

```
- name: Add Oracle Java PPA
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags: java
- name: Install Oracle Java
  apt: name=oracle-java7-installer state=present update_cache=yes
  tags: java
```

**Comment by alanorth** [comment]
Yeah, I'm not sure on the cache... I think 1 hour is good. 24 hours might be too long for us to notice that we're saving time, but long enough to start missing updated packages in re-runs of playbooks.

**Comment by oguya** [comment]
I've changed the `cache_valid_time` to 1HR.
