### ISSUE TITLE
Allow DSpace role to deploy by default

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#7]
There are at least a few critical variables (atmire!) which need to be defined or else the playbook will fail. It's better to let the playbook deploy successfully (so all notifies fire, for example) but have the application not fully configured, than to have the deploy die!

**Comment by oguya** [comment]
I guess it's just  a matter of coming up with default values for the variables defined in `host_vars`.

**Comment by alanorth** [comment]
Or skipping the task if it's not defined...

**Comment by alanorth** [comment]
For `apt_mirror` it makes sense to have a default. But for private things like the maven repo credentials there is no sensible default. So we either skip it (and fail during DSpace build) or make it a private group var.

**Comment by oguya** [comment]
Definitely `private/vars/$GROUP`. Remember, we're also interested in uncluttering `host_vars`.

**Comment by alanorth** [comment]
True, perhaps we could use `private/vars/$group` and also only run the task
if that variable exists, then we kinda get the benefit of both approaches.
I guess that pattern would become common -- tasks depending on private
variables would generally become optional. Then anyone using our playbooks
would still be able to deploy them without stumbling on privates...

**Comment by oguya** [comment]
Ok, I've created a new branch -- [dspace](https://github.com/ilri/rmg-ansible-public/tree/dspace) -- where we'll make all the necessary changes & if all is well, merge to master.

**Comment by oguya** [comment]
After adding the following variables to `defaults/main.yml`, I was able to successfully run the dspace role with only `ansible_ssh_host` in `host_vars`:
1. dspace webapps
   
   ```
   dspace_webapps:
     - { name: 'ROOT', app_path: '/home/{{ nginx_server_name }}/webapps/xmlui', context_path: '/etc/tomcat7/Catalina/localhost/ROOT.xml' }
     - { name: 'jspui', app_path: '/home/{{ nginx_server_name }}/webapps/jspui', context_path: '/etc/tomcat7/Catalina/localhost/jspui.xml' }
     - { name: 'oai', app_path: '/home/{{ nginx_server_name }}/webapps/oai', context_path: '/etc/tomcat7/Catalina/localhost/oai.xml' }
     - { name: 'solr', app_path: '/home/{{ nginx_server_name }}/webapps/solr', context_path: '/etc/tomcat7/Catalina/localhost/solr.xml' }
     - { name: 'rest', app_path: '/home/{{ nginx_server_name }}/webapps/rest', context_path: '/etc/tomcat7/Catalina/localhost/rest.xml' }
   ```
2. postgresql dspace db credentials
   
   ```
   dspace_db_name: dspace
   dspace_db_user: dspace
   dspace_db_password: e\`aJ+C4wMUY;2R-
   ```
3. nginx server name & document root
   
   ```
   nginx_server_name: localhost
   nginx_root: /home/{{ nginx_server_name }}/webapps/xmlui
   ```

**Comment by alanorth** [comment]
Merged and updated a lot of your code, for example I added `dspace_root`. Also, I updated the host_vars for the DSpace hosts to use the new variable and exclude the ones defined in defaults.

Need to test a clean DSpace machine to see if it can deploy without all of our settings, but this was good work, we caught a few things and made the role more robust and simple.
