### ISSUE TITLE
Migrating Azizi from CentOS 6 to Ubuntu 14.04

### ISSUE THREAD

**Issue by oguya** [ilri/rmg-ansible-public#8]
We need to test the following items before migrating Azizi to Ubuntu 14.04:
- [x] labcollector/ioncube
- [x] repository website
- [x] pdf printing - wkhtml2pdf
- [x] scripts, cronjobs
- [x] wordpress (tdg) can't we just move it linode03?

Packages/softwares needed:
- [x] apache2 web server
- [x] php5 & its modules
- [x] mysql & postgresql client/common tools
- [x] sssd & ldap tools

**Comment by oguya** [comment]
- spun up a test vm
  
  ```
  virt-install --name=azizi-test \
  --description "Internal IP: 192.168.10.229. Test azizi migration to ubuntu 14.04" \
  --ram=1024 --vcpus=1 \
  --os-type=Linux --accelerate \
  --network bridge=br0,model=virtio --autostart --graphics spice \
  --disk /var/lib/libvirt/images/azizi-test,device=disk,bus=virtio,format=qcow2,size=30 \
  --location http://ubuntu.mirror.ac.ke/ubuntu/dists/trusty/main/installer-amd64/ \
  --extra-args="auto=true priority=critical url=http://192.168.10.23/preseeds/ubuntu-14.ks interface=eth0 hostname=azizi-test netcfg/get_ipaddress=192.168.10.229 netcfg/get_netmask=255.255.255.0 netcfg/get_gateway=192.168.10.254 netcfg/get_nameservers=8.8.8.8 netcfg/disable_dhcp=true"
  ```
- installed apache2 & sssd from web & sssd roles
- installed php5
  
  ```
  aptitude install php5 php5-common php5-cli php5-mysql php5-pgsql php5-ldap php5-curl
  ```
- mysql & postgresql client/common tools
  
  ```
  aptitude install postgresql-client mysql-client
  ```

**Comment by oguya** [comment]
- installed wkhtml2pdf - for pdf printing
  
  ```
  wget http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  dpkg --install wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  apt-get install -f
  ```

**Comment by jasonrogena** [comment]
- Install NPM and Bower

```
apt-get install npm nodejs-legacy 
npm install bower -g
```

**Comment by alanorth** [comment]
nodejs-legacy?!

**Comment by jasonrogena** [comment]
The Debian team renamed the Nodejs binary to 'nodejs' (called 'node' in RHL distros). Bower fails to work, by default, with this. [nodejs-legacy takes care of that](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907#108). I could also symlink  /usr/bin/nodejs -> /usr/bin/node but that looked a bit hacky

**Comment by alanorth** [comment]
Ok, fair enough!

**Comment by jasonrogena** [comment]
Install CPAN's Excel Writer module for printing of labels

```
cpan i Excel:Writer:XLSX
```

**Comment by jasonrogena** [comment]
Install dependencies for pyxform

```
apt-get install python-pip python-dev libxml2-dev libxslt1-dev openjdk-7-jre-headless
pip install xlrd
pip install -e git+https://github.com/XLSForm/pyxform.git@master#egg=pyxform
```

**Comment by soloincc** [comment]
Install labcollector
1. Download labcollector from http://labcollector.com/download-labcollector-software/
2. Get the ioncube loaders from http://www.ioncube.com/loaders.php
3. Install and configure PHP to use the loaders by following the instructions at http://www.ioncube.com/loaders.php

**Comment by oguya** [comment]
We've already moved the entire [azizi.ilri.org](http://azizi.ilri.org) website & its dependencies to a clean Ubuntu 14.04 VM.
Thanks a lot gents for making this happen :+1:

**Comment by alanorth** [comment]
Just in time for Ubuntu 16.04!

On Mon, Feb 29, 2016 at 10:16 AM James Oguya notifications@github.com
wrote:

> Closed #8 https://github.com/ilri/rmg-ansible-public/issues/8.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ilri/rmg-ansible-public/issues/8#event-570637660.
> 
> ## 

Alan Orth
alan.orth@gmail.com
https://englishbulgaria.net
https://alaninkenya.org
https://mjanja.ch

**Comment by oguya** [comment]
@alanorth If Ubuntu 16.04 ships with PHP 7, then the upgrade might break a tonne of azizi's php scripts.

**Comment by alanorth** [comment]
Ubuntu LTS is not Fedora (it doesn't ship with the latest shit at the time
of release). It has to support the packages it ships with for five years.
Anyways, Ubuntu 16.04 will have mod-php5 as 5.6, with 7.0 as a separate
option:

http://packages.ubuntu.com/xenial/httpd/libapache2-mod-php5

On Mon, Feb 29, 2016 at 10:25 AM James Oguya notifications@github.com
wrote:

> @alanorth https://github.com/alanorth If Ubuntu 16.04 ships with PHP 7,
> then the upgrade might break a tonne of azizi's php scripts.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ilri/rmg-ansible-public/issues/8#issuecomment-190093798
> .
> 
> ## 

Alan Orth
alan.orth@gmail.com
https://englishbulgaria.net
https://alaninkenya.org
https://mjanja.ch
