### ISSUE TITLE
Add solr-5.2.x support

### ISSUE THREAD

**Issue by oguya** [ilri/rmg-ansible-public#9]
At the moment we only have `solr-5.1.0` branch which is 2 versions[1] behind of the latest `solr-5.2.1`.
1. https://archive.apache.org/dist/lucene/solr/

**Comment by oguya** [comment]
solr does point releases, so instead of creating each branch for each point release, I think we can have  a `$MAJOR_VERSION-$MINOR_VERSION-x` convention for naming solr branches.

Therefore, `solr-5.2.0` and `solr-5.2.1` would be in `solr-5.2.x` branch.

**Comment by alanorth** [comment]
Sure, makes sense. In the end the idea is to merge to master anyways, so branch names only need to make sense for the duration they exist.

**Comment by qlands** [comment]
I am testing CKAN on Solr 5.2.X . Since Solr5 can work in schema less mode I am checking what it takes to have a core with the CKAN schema. I let you know

**Comment by alanorth** [comment]
:+1: @qlands. Another benefit of Solr 5+ is that it doesn't need Tomcat. This makes the deployment simpler but we have to test migration path from 4.10.x for your and @jasonrogena Solr instances.

**Comment by oguya** [comment]
Ok, I've managed to deploy `solr-5.2.1`  from [solr-5.2.x branch](https://github.com/ilri/rmg-ansible-public/tree/solr-5.2.x). Time to do some tests.

**Comment by jasonrogena** [comment]
Did a bit of testing on our cores. Deploy or die Gents

**Comment by oguya** [comment]
We need to start testing solr 5.3.0[1] which was released a few weeks ago.
Otherwise, if no one's having issues with deploying solr 5.2.x, then I think we should close this issue.
1. https://archive.apache.org/dist/lucene/solr/5.3.0/
